### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by dariomas**

### CODE REVIEW

**Comment by dariomas** [comment]
I think that the Travis check error does not depend on the files I have updated.
Please let me know how I can help resolve the issue, thanks.

**Comment by dariomas** [comment]
Closing because the PR has been merged anyway.
Thanks,
     Dario_

**Comment by tvalenta** [comment]
@dariomas You are correct that your PR was not the cause of the Travis failure. I've fixed the Travis build itself, but there is still a test failure which is occurring. Your PR should still fail the test, however we are looking into that issue.

**Comment by dariomas** [comment]
Thank you @tvalenta 
Let me know if I can help somehow.
 
> @dariomas You are correct that your PR was not the cause of the Travis failure. I've fixed the Travis build itself, but there is still a test failure which is occurring. Your PR should still fail the test, however we are looking into that issue.

**Comment by dariomas** [comment]
Hi @tvalenta ,
I was trying again to merge my PR  but during the build Travis is failing:

`> Configure project :app
Checking the license for package Android SDK Build-Tools 28.0.3 in /usr/local/android-sdk/licenses
Warning: License for package Android SDK Build-Tools 28.0.3 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;28.0.3 Android SDK Build-Tools 28.0.3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.`

What I can do to help you?

Thanks_

**Comment by AnthonyRonning** [comment]
Hi @dariomas, 

I think it's something we can attempt to fix or can mitigate, but I do have a question. Have you taken a look at the iOS wallet at all to add translations there too? 

It would be nice if we could maintain feature parity amongst the mobile apps.

**Comment by dariomas** [comment]
Hi @AnthonyRonning,
thank you to help, let me know when to build again this PR.

About the iOS version would be very useful to have the Italian language too, but I do not have the Apple SDK and environment; anyway I could check the language strings and upload the translations, that are the same as these, but somebody have to edit the iOS App sources.
Let me know how to help.

Thanks,
   Dario_

> Hi @dariomas,
> 
> I think it's something we can attempt to fix or can mitigate, but I do have a question. Have you taken a look at the iOS wallet at all to add translations there too?
> 
> It would be nice if we could maintain feature parity amongst the mobile apps.

**Comment by AnthonyRonning** [comment]
Thanks @dariomas. Check out the below in order to get an idea of how you would add translations to iOS. 

Our english copy is located here: https://github.com/blockchain-certificates/wallet-iOS/blob/master/wallet/Base.lproj/Localizable.strings

And here's an example of what our spanish translations look like: https://github.com/blockchain-certificates/wallet-iOS/tree/master/wallet/es.lproj

If you can get a branch going with these changes, I can do the build and look through the app to make sure that everything is in order before merging it in.

**Comment by dariomas** [comment]
Thank you @AnthonyRonning  
with your help I'm working now on iOS App strings, but I can complete the translations next week.

Please keep me informed about the Travis build and Unit Test problem for this PR.

 See you soon.

> Thanks @dariomas. Check out the below in order to get an idea of how you would add translations to iOS.
> 
> Our english copy is located here: https://github.com/blockchain-certificates/wallet-iOS/blob/master/wallet/Base.lproj/Localizable.strings
> 
> And here's an example of what our spanish translations look like: https://github.com/blockchain-certificates/wallet-iOS/tree/master/wallet/es.lproj
> 
> If you can get a branch going with these changes, I can do the build and look through the app to make sure that everything is in order before merging it in.

**Comment by dariomas** [comment]
Hi All,
did you check if my translations are working?

Thanks_

**Comment by AnthonyRonning** [comment]
My apologies for the delay. There was a problem with the latest version of cert-verifier-js that was causing issues with the mobile apps, and we needed the new translations from there in order for E2E translations to be complete. 

I'm hoping to knock out all of the testing required for the new version of cert-verifier-js this Friday. From the outside though, I think all of the language stuff you made is good, just dependency testing is needed right now.

**Comment by AnthonyRonning** [comment]
Tested and merged with japanese in this PR: https://github.com/blockchain-certificates/wallet-android/pull/45

Preparing it for beta in the google play store now.

**Pull request closed without merging**
